labels:
  - name: "add mod"
    conditions:
      - body: '^- \[x\] Add mod to alternatives page$'
  - name: "enhancement"
    conditions:
      - body: '^- \[x\] Site changes$'
  - name: "documentation"
    conditions:
      - body: '^- \[x\] Chore/documentation updates$'
  - name: "BREAKING CHANGE"
    conditions:
      - body: '^- \[x\] Tick this box if you made changes that may or may not break site functionality.$'
  - name: "Merge conflict identified"
    conditions:
      - mergeable: false
