labels:
  - name: "add mod"
    conditions:
      - body: "^-\s\[x\] Add mod to alternatives page$"
  - name: "enhancement"
    conditions:
      - body: "^-\s\[x\] Site changes$"
  - name: "documentation"
    conditions:
      - body: "^-\s\[x\] Chore/documentation updates$"
  - name: "BREAKING CHANGE"
    conditions:
      - body: "^-\s\[x\] Tick this box if you made changes that may or may not break site functionality\.$"
  - name: "Merge conflict identified"
    conditions:
      - mergeable: false
