name: Crowdin translations stuff

run-name: Update from Crowdin

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
    contents: write

jobs:
  crowdin-translations-progress:
    name: Crowdin translations progress updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Crowdin translations progress markdown
        uses: benjaminjonard/crowdin-translations-progress-action@1.0.7
        with:
          languages_per_row: 10
          minimum_completion_percent: 80
          file: README.md
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Push changes
        uses: actions-go/push@v1
        with:
          author-name: Actionsbot
          author-email: actions@github.com
          commit-message: 'Update Crowdin translation progress badge'
          remote: origin

  update-from-crowdin:
    name: Update strings from Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Grab strings from Crowdin
        uses: crowdin/github-action@v2.0.0
        with:
            config: crowdin.yml
            upload_sources: true
            upload_translations: false
            upload_language: us
            download_sources: true
            download_translations: true
            skip_untranslated_files: true
            skip_untranslated_strings: true
            export_only_approved: true
            localization_branch_name: i18n-crowdin-translations
            create_pull_request: true
            pull_request_title: (Crowdin Action) New translation strings
            pull_request_body: New translated strings are now available!
            pull_request_labels: crowdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}